version: v2
managed:
    enabled: true
plugins:
    - local: protoc-gen-ts_proto
      out: ./libs/common/src/types
      strategy: all
      opt:
          - outputServices=nice-grpc,outputServices=generic-definitions
          - useExactTypes=true
          - useOptionals=all
          - addGrpcMetadata=true
inputs:
    - directory: ./proto
